---
- set_fact: nos="{{ hostvars[inventory_hostname]['ansible_network_os'] }}"

- name: nxos_command
  nxos_command:
    commands:
      - "show {{ item.cmd }}"
  with_items:
    - "{{ nxos }}"
  when: ansible_network_os == 'nxos' and nos == 'nxos'

- name: eos_command
  eos_command:
    commands:
      - "show {{ item.cmd }}"
  with_items:
    - "{{ eos }}"
  when: ansible_network_os == 'eos' and nos == 'eos'

- name: ios_command
  ios_command:
    commands:
      - "show {{ item.cmd }}"
  with_items:
    - "{{ ios }}"
  when: ansible_network_os == 'ios' and nos == 'ios'

- name: vyos_command
  vyos_command:
    commands:
      - "show {{ item.cmd }}"
  with_items:
    - "{{ vyos }}"
  when: ansible_network_os == 'vyos' and nos == 'vyos'

- name: junos_command
  junos_command:
    commands:
      - "show {{ item.cmd }}"
  with_items:
    - "{{ junos }}"
  when: ansible_network_os == 'junos' and nos == 'junos'
